### PR TITLE
Add facts about Primrose (bird)

### PR DESCRIPTION
**Pull request by beechnut**
She's a bird, but the good people of TTS need facts about her.

### CODE REVIEW

**Comment by mgwalker** [comment]
Do you want to add Primrose to the dag facts, or would you rather create a new bird facts bot? Maybe there are more birds at TTS! I'm not opposed to Primrose playing with the dogs, though. Your call!

Now I'm also thinking we should have a consolidated "pet fact" bot. 🤔

**Comment by beechnut** [comment]
@mgwalker I was wondering about the same thing! If we made `birds.json`, would it be possible to request a bird fact in #dags? #discuss-birdtalk is sparsely populated and I feel like dag-havers will be amused by the addition of a bird.

**Comment by mgwalker** [comment]
Certainly, people can ask for whatever kind of fact wherever they want! But that said, I was amused to see a bird amongst the dog facts. It seems like the sort of place a bird would show up, really.

**Comment by beechnut** [comment]
Ok great! I'm going to close this and I'll open a new one with bird facts in a separate file.

**Pull request closed without merging**
